### ISSUE TITLE
BG Koh : Référence fabricant sur Articles

### ISSUE THREAD

**Issue by d4e-ch** [d4e-digital-4-efficiency/BG-Research#1]
Salut Rihab !

Il faudrait ajouter un champ **Référence fournisseur** sur la fiche Article :

![image](https://user-images.githubusercontent.com/52782157/134194944-956810d3-c441-4771-858c-e3f55c9ec357.png)

- [x] Il faut qu'on puisse rechercher par cette référence dans la vue _Tree_ **Articles**.

- [x] Sur les Purchase Order, la Description sur la ligne doit reprendre cette référence ainsi "Référence fabricant : xxxxxx". Par exemple :
![image](https://user-images.githubusercontent.com/52782157/134195247-f29b2c05-c876-4f39-9b8b-25195b1f25cb.png)

Merci !!

**Comment by rihabjl** [comment]
Bonjour,
Pouvez-vous me donner l'accès au projet "BG Koh" sur odoo.sh?
Merci!

**Comment by d4e-ch** [comment]
Oups, c'est fait !

**Comment by rihabjl** [comment]
Hello,

C'est fait sur le staging rec-210629
Module: d4e_reference_field
Commit : d6cbbbc

Merci.

**Comment by d4e-ch** [comment]
@Le-Koala Peux tu tester et passer en prod si c'est OK stp ?
Je l'ai promis pour ce matin...

**Comment by Le-Koala** [comment]
Hello Rihab,

Peux-tu stp modifier le nom vers Manufacturer Reference et ajouter la traduction Référence Fabricant stp
Il faudrait aussi ajouter le champs sur cette vue stp
![image](https://user-images.githubusercontent.com/64476230/134469927-5af71ae2-3458-4f06-8f6e-81d12720fdbd.png)

Merci

**Comment by Le-Koala** [comment]
@d4e-ch MeP faiet en attendant modifs

**Comment by rihabjl** [comment]
Bonjour,

C'est fait sur le staging rec-210629
Module: d4e_reference_field
Commit : 9eb9533

Merci.
